---
# tasks file for squid

- name: include ~> setup for {{ ansible_os_family }}
  include: "setup-{{ ansible_os_family }}.yml"

- name: package ~> install squid
  package:
    name: squid
    state: present

- name: service ~> enabled and stopped
  service:
    name: squid
    enabled: true
    state: started

- name: file ~> check if directory already created
  stat:
    path: "{{ squid_cache_dirs[0].dir }}"
  register: squid_cache_dirs_first

- name: file ~> cache dir setup
  file:
    path: "{{ item.dir }}"
    state: directory
    owner: "{{ squid_user }}"
    group: "{{ squid_group }}"
    mode: "0644"
  loop: "{{ squid_cache_dirs }}"
  when: not squid_cache_dirs_first.stat.exists

# @todo provide a way to generate cache dir properly
- name: template ~> create config
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid-test.conf
    owner: "{{ squid_user }}"
    group: "{{ squid_group }}"
    backup: true
