---
# handlers file for squid
- name: generate cache
  command: squid -z

- name: start service
  service:
    name: squid
    state: started

- name: stop squid
  service:
    name: squid
    state: stopped
