---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
  roles:
    - role: squid
  vars:
    squid_cache_dirs:
    - dir: /srv/cache/disk1
      type: aufs
      options: 5000 24 256
    - dir: /srv/cache/disk2
      type: aufs
      options: 5000 24 256
