---
- name: Converge
  hosts: all
  become: true
  pre_tasks:

    - name: include os family tasks
      include: "./include/{{ ansible_os_family }}.yml"

    - name: install wget
      package: name=wget state=present

  roles:
    - role: squid
  vars:
    squid_configure_firewall: true
    squid_cache_dirs:
    - dir: /srv/cache/disk1
      type: aufs
      options: 5000 24 256
    - dir: /srv/cache/disk2
      type: aufs
      options: 5000 24 256
